version: '2'
services:
    mvnblog-app:
        image: mvnblog
        external_links:
            - mvnblog-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/mvnblog?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mvnblog-mysql:
        extends:
            file: mysql.yml
            service: mvnblog-mysql
