version: '2'
services:
    httpdemo-app:
        image: httpdemo
        external_links:
            - httpdemo-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/httpdemo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    httpdemo-mysql:
        extends:
            file: mysql.yml
            service: httpdemo-mysql
